@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(pbc, "Usuário do Sistema", "Um usuario (atendente ou cliente) já cadastrado no sistema")
System_Boundary(ibs, "Sistema da Ong") {
    Container(wa, "Aplicação Web","php", "Permite ao usuário utilizar todas as funçoes do sistema via browser")
    Container(ma, "Mobile App","java", "Permite ao usuário utilizar o sistema via aplicativo mobile")
    Container(db, "Banco de Dados", "Relational Database Schema", "Guarda as informações do sistema.")
    
    Rel(wa, db, "Lê e escreve os dados")
    Rel(ma, db, "Lê e escreve os dados")
}

Rel(pbc, wa, "Usa")
Rel(pbc, ma, "Usa")
@enduml
